# Generated by Django 2.2 on 2019-04-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='roll_number',
            field=models.CharField(max_length=255),
        ),
    ]
