# Generated by Django 2.2 on 2019-04-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_appuser_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
