# Generated by Django 2.2 on 2019-04-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190419_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='picture',
        ),
    ]
