# Generated by Django 2.2 on 2019-04-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_appuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/'),
        ),
    ]
