# Generated by Django 2.2 on 2019-04-27 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190427_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_image', to='api.Attendance'),
        ),
    ]
