# Generated by Django 2.2 on 2019-04-30 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190427_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='api.Attendance'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
