# Generated by Django 2.2 on 2019-05-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190430_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='DJImage',
        ),
    ]
