# Generated by Django 2.2 on 2019-05-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190501_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='num_present',
            field=models.IntegerField(default=0),
        ),
    ]
